# Generated by Django 5.1.4 on 2024-12-21 04:58

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384),
        ),
    ]
