# Generated by Django 5.1.4 on 2025-01-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_pinecone_id_course_total_lessons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonvideo',
            old_name='url',
            new_name='video_url',
        ),
    ]
