# Generated by Django 5.1.4 on 2025-01-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=130, null=True),
        ),
    ]
