# Generated by Django 5.1.4 on 2025-01-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_instructor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='name',
            new_name='full_name',
        ),
    ]
